services:
  - type: web
    name: meals-on-the-way-frontend
    env: static
    rootDir: meals-on-the-way
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: "https://newbackend.onrender.com/api" # Remember to update this with your actual backend URL in the Render Dashboard
      - key: CI
        value: "false"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
